CREATE TABLE "JAS"."CHATS"
   (	"CHAT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
	"FROM_USER" NVARCHAR2(50) NOT NULL ENABLE,
	"MESSAGE" NVARCHAR2(250) NOT NULL ENABLE,
	"DATE_CREATED" DATE NOT NULL ENABLE,
	"RECEIVED" NUMBER(1,0) NOT NULL ENABLE,
	 CONSTRAINT "CHAT_PK" PRIMARY KEY ("CHAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXTABLESPACE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXTABLESPACE" ;
  CREATE UNIQUE INDEX "JAS"."CHAT_PK" ON "JAS"."CHATS" ("CHAT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXTABLESPACE" ;
  ALTER TABLE "JAS"."CHATS" ADD CONSTRAINT "CHAT_PK" PRIMARY KEY ("CHAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAXTABLESPACE"  ENABLE;
  ALTER TABLE "JAS"."CHATS" MODIFY ("RECEIVED" NOT NULL ENABLE);
  ALTER TABLE "JAS"."CHATS" MODIFY ("DATE_CREATED" NOT NULL ENABLE);
  ALTER TABLE "JAS"."CHATS" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "JAS"."CHATS" MODIFY ("FROM_USER" NOT NULL ENABLE);
  ALTER TABLE "JAS"."CHATS" MODIFY ("CHAT_ID" NOT NULL ENABLE);